### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nvahalik** [n0vabyte/Linode_Netv4_Keepalived#1]
Hey, this was a great article. I wanted to add a few notes—LMK if you'd like a PR in case this would help someone else.

We run Debian so I had to go into `/etc/network/interfaces` and add the shared IP to the `lo  interface`:

    # Add Shared IP Address
    iface lo inet static
        address x.x.x.x/32

If you're running `keepalived`, it doesn't seem like you need to change your config file at all. It'll keep working—it just won't actually manage the IP anymore.

For sudo, we created `/etc/sudoers.d/keepalived_script`:

```
keepalived_script ALL=NOPASSWD: /usr/bin/systemctl stop lelastic, /usr/bin/systemctl restart lelastic
```

Also, the "main thing" you need to change in your `keepalived` scripts is that when assuming the `master` role, you will want to start `lelastic` and when you're not `master`, you'll want to stop it.

**Comment by n0vabyte** [comment]
Hi Nick  -

Thanks for opening the issue :) When you are configuring a shared a IP, you typically don't want to statically configure this and should be left for keepalived.  

> Also, the "main thing" you need to change in your keepalived scripts is that when assuming the master role, you will want to start lelastic and when you're not master, you'll want to stop it.

Actually, this is happening already in the [notify.sh](https://github.com/n0vabyte/Linode_Netv4_Keepalived/blob/main/files/notify.sh#L12) .  Unless you are the primary, lelastic is stopped.

**Comment by nvahalik** [comment]
@n0vabyte So are the main Linode docs needing to be updated? I just followed the directions there.
